import { PrismaClient } from '@prisma/client';
const db=new PrismaClient(); const data: Record<string,string[]>={
'Faculty of Agriculture & Life Sciences':['Agricultural Economics & Extension','Animal Production & Health','Crop Production & Protection','Fisheries & Aquaculture','Food Science & Technology','Forestry & Wildlife Management','Soil Science & Land Resources Management'],
'Faculty of Bio-Sciences':['Biochemistry','Biology/Biological Sciences','Biotechnology','Botany','Microbiology','Zoology'],
'Faculty of Computing & Information System':['Computer Science','Information Technology','Information Systems','Cyber Security','Software Engineering'],
'Faculty of Education':['Educational Foundations','Curriculum Studies','Educational Psychology','Guidance & Counselling','Science & Technical Education','Chemistry Education','Mathematics Education','Physics Education'],
'Faculty of Engineering':['Agricultural Engineering','Chemical Engineering','Civil Engineering','Computer Engineering','Mechanical Engineering'],
'Faculty of Humanities':['African Traditional Religion','Christian Religious Studies','English & Literary Studies','History & Diplomatic Studies','Islamic Religious Studies','Philosophy'],
'Faculty of Law':['Public & International Law','Private & Commercial Law'],'Faculty of Management Sciences':['Accounting','Banking & Finance','Business Administration','Hospitality & Tourism Management','Public Administration'],'Faculty of Physical Sciences':['Chemistry','Industrial Chemistry','Mathematics','Pure & Applied Physics','Statistics'],'Faculty of Social Sciences':['Economics','Library & Information Science','Political Science','Sociology'],
'Faculty of Basic Medical Sciences':['Human Anatomy','Human Physiology'],'Faculty of Allied Health Sciences':['Medical Laboratory Science','Physiotherapy'],'Faculty of Clinical Sciences':['Medicine','Surgery','Community Medicine','Family Medicine','Paediatrics'],'Faculty of Basic Clinical Sciences':['Medical Biochemistry','Chemical Pathology','Histopathology','Haematology','Pharmacology/Therapeutics','Microbiology']};
const slug=(v:string)=>v.toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,''); async function main(){for(const [name,depts] of Object.entries(data)){const f=await db.faculty.upsert({where:{name},update:{},create:{name,slug:slug(name)}}); for(const name of depts)await db.department.upsert({where:{slug:slug(f.name+'-'+name)},update:{},create:{name,slug:slug(f.name+'-'+name),facultyId:f.id}})} await db.academicSession.upsert({where:{name:'2025/2026'},update:{isActive:true},create:{name:'2025/2026',isActive:true}})} main().finally(()=>db.$disconnect());
