import 'dotenv/config'; import express from 'express'; import helmet from 'helmet'; import cors from 'cors'; import rateLimit from 'express-rate-limit'; import { PrismaClient } from '@prisma/client'; import argon2 from 'argon2'; import jwt from 'jsonwebtoken'; import { z } from 'zod';
// LEGACY API FOUNDATION — NOT DEPLOYED. The deployed runtime is the static SPA
// + Supabase (RLS) + edge functions. This file is retained for local/dev use.
if (!process.env.JWT_ACCESS_SECRET || process.env.JWT_ACCESS_SECRET.length < 16) {
  console.error('FATAL: JWT_ACCESS_SECRET is missing or too weak (min 16 chars). Refusing to start.');
  process.exit(1);
}
if (!process.env.DATABASE_URL) { console.error('FATAL: DATABASE_URL is missing. Refusing to start.'); process.exit(1); }
const db=new PrismaClient(), app=express(); app.use(helmet()); app.use(cors({origin:process.env.CLIENT_URL,credentials:true})); app.use(express.json({limit:'1mb'})); app.use('/api',rateLimit({windowMs:15*60*1000,max:300}));
const data=db as any; const audit=(userId:string|undefined,action:string,entity:string,entityId?:string,metadata?:object)=>data.auditLog.create({data:{userId,action,entity,entityId,metadata}}).catch(()=>undefined);
const sign=(id:string,role:string)=>jwt.sign({sub:id,role},process.env.JWT_ACCESS_SECRET!,{expiresIn:'15m'});
function auth(req:any,res:any,next:any){try{const token=req.headers.authorization?.split(' ')[1]; req.user=jwt.verify(token,process.env.JWT_ACCESS_SECRET!);next()}catch{return res.status(401).json({message:'Authentication required'})}}
function admin(req:any,res:any,next:any){if(!['ADMIN','SUPER_ADMIN','LIBRARIAN'].includes(req.user?.role))return res.status(403).json({message:'Insufficient permissions'});next()}
app.get('/api/health',(_q,r)=>r.json({status:'ok'}));
app.post('/api/auth/register',async(req,res)=>{const parsed=z.object({fullName:z.string().min(2),displayName:z.string().min(2),email:z.string().email(),password:z.string().min(8),matricNumber:z.string().min(4),facultyId:z.string(),departmentId:z.string(),level:z.string().optional()}).safeParse(req.body); if(!parsed.success)return res.status(422).json({errors:parsed.error.flatten()}); try{const u=await db.user.create({data:{...parsed.data,passwordHash:await argon2.hash(parsed.data.password)} as any});res.status(201).json({accessToken:sign(u.id,u.role),user:{id:u.id,fullName:u.fullName,email:u.email,role:u.role}})}catch{return res.status(409).json({message:'Email or matric number already registered'})}});
app.post('/api/auth/login',async(req,res)=>{const p=z.object({identifier:z.string(),password:z.string()}).safeParse(req.body);if(!p.success)return res.status(422).json({message:'Invalid credentials'});const u=await db.user.findFirst({where:{OR:[{email:p.data.identifier},{matricNumber:p.data.identifier}]}});if(!u||!await argon2.verify(u.passwordHash,p.data.password)||!(u as any).isActive)return res.status(401).json({message:'Invalid credentials'});await data.user.update({where:{id:u.id},data:{lastLoginAt:new Date(),lastActivityAt:new Date()}});await audit(u.id,'LOGIN','USER',u.id);res.json({accessToken:sign(u.id,u.role),user:{id:u.id,fullName:u.fullName,email:u.email,role:u.role}})});
app.get('/api/auth/me',auth,async(req:any,res)=>res.json(await db.user.findUnique({where:{id:req.user.sub},select:{id:true,fullName:true,email:true,role:true,matricNumber:true}})));
app.put('/api/auth/me',auth,async(req:any,res)=>{const p=z.object({displayName:z.string().min(2).optional(),bio:z.string().max(500).optional(),profilePictureUrl:z.string().url().optional()}).safeParse(req.body);if(!p.success)return res.status(422).json({errors:p.error.flatten()});res.json(await db.user.update({where:{id:req.user.sub},data:p.data as any}))});
app.post('/api/auth/me/student-id',auth,async(req:any,res)=>{const p=z.object({studentIdUrl:z.string().url()}).safeParse(req.body);if(!p.success)return res.status(422).json({message:'A valid student ID URL is required'});res.json(await db.user.update({where:{id:req.user.sub},data:{...p.data,verificationStatus:'PENDING'} as any}))});
app.get('/api/admin/verifications',auth,admin,async(_req,res)=>res.json(await db.user.findMany({where:{verificationStatus:'PENDING'} as any,select:{id:true,fullName:true,email:true,matricNumber:true,studentIdUrl:true,createdAt:true}})));
app.patch('/api/admin/verifications/:id',auth,admin,async(req,res)=>{const p=z.object({approved:z.boolean()}).safeParse(req.body);if(!p.success)return res.status(422).json({message:'approved is required'});res.json(await db.user.update({where:{id:req.params.id},data:{verificationStatus:p.data.approved?'VERIFIED':'REJECTED',isVerified:p.data.approved} as any}))});
app.get('/api/faculties',async(_q,res)=>res.json(await db.faculty.findMany({include:{departments:true},orderBy:{name:'asc'}})));
app.get('/api/departments',async(req,res)=>res.json(await db.department.findMany({where:req.query.facultyId?{facultyId:String(req.query.facultyId)}:{},include:{faculty:true}})));
app.get('/api/courses',async(req,res)=>res.json(await db.course.findMany({where:req.query.departmentId?{departmentId:String(req.query.departmentId)}:{},include:{department:true}})));
app.get('/api/users',auth,admin,async(_req,res)=>res.json(await db.user.findMany({select:{id:true,fullName:true,email:true,matricNumber:true,role:true,isVerified:true,createdAt:true}})));
app.get('/api/users/:id',auth,admin,async(req,res)=>{const user=await data.user.findUnique({where:{id:req.params.id},include:{faculty:true,department:true,auditLogs:{take:30,orderBy:{createdAt:'desc'}},bookmarks:true,downloads:true,views:true}});if(!user)return res.status(404).json({message:'User not found'});res.json(user)});
app.patch('/api/users/:id/status',auth,admin,async(req:any,res)=>{const p=z.object({isActive:z.boolean()}).safeParse(req.body);if(!p.success)return res.status(422).json({message:'isActive is required'});const u=await data.user.update({where:{id:req.params.id},data:p.data});await audit(req.user.sub,p.data.isActive?'USER_REACTIVATED':'USER_SUSPENDED','USER',u.id);res.json(u)});
app.get('/api/admin/dashboard',auth,admin,async(_req:any,res)=>{const month=new Date();month.setDate(1);month.setHours(0,0,0,0);const [students,verified,pending,faculties,departments,courses,materials,monthly,recent,activities]=await Promise.all([data.user.count({where:{role:'STUDENT'}}),data.user.count({where:{role:'STUDENT',verificationStatus:'VERIFIED'}}),data.user.count({where:{role:'STUDENT',verificationStatus:'PENDING'}}),data.faculty.count(),data.department.count(),data.course.count(),data.material.count(),data.material.count({where:{createdAt:{gte:month}}}),data.user.findMany({where:{role:'STUDENT'},take:8,orderBy:{createdAt:'desc'},select:{id:true,fullName:true,displayName:true,email:true,createdAt:true,verificationStatus:true}}),data.auditLog.findMany({take:10,orderBy:{createdAt:'desc'},include:{user:{select:{fullName:true,displayName:true,role:true}}}})]);res.json({stats:{students,verified,pending,faculties,departments,courses,materials,monthly},recent,activities})});
app.get('/api/admin/audit-logs',auth,admin,async(req,res)=>res.json(await data.auditLog.findMany({take:Math.min(100,Number(req.query.limit)||50),orderBy:{createdAt:'desc'},include:{user:{select:{fullName:true,displayName:true,role:true}}}})));
app.get('/api/admin/settings',auth,admin,async(_req,res)=>res.json(await data.systemSetting.findMany({orderBy:{key:'asc'}})));
app.put('/api/admin/settings/:key',auth,admin,async(req:any,res)=>{const p=z.object({value:z.any()}).safeParse(req.body);if(!p.success)return res.status(422).json({message:'value is required'});const setting=await data.systemSetting.upsert({where:{key:req.params.key},update:{value:p.data.value,updatedById:req.user.sub},create:{key:req.params.key,value:p.data.value,updatedById:req.user.sub}});await audit(req.user.sub,'SETTINGS_UPDATED','SYSTEM_SETTING',setting.id,{key:req.params.key});res.json(setting)});
app.post('/api/faculties',auth,admin,async(req,res)=>{const p=z.object({name:z.string().min(2),description:z.string().optional()}).safeParse(req.body);if(!p.success)return res.status(422).json({errors:p.error.flatten()});const slug=p.data.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');res.status(201).json(await db.faculty.create({data:{...p.data,slug}}))});
app.put('/api/faculties/:id', auth, admin, async (req, res) => { const p = z.object({ name: z.string().min(2).optional(), description: z.string().optional() }).safeParse(req.body); if (!p.success) return res.status(422).json({ errors: p.error.flatten() }); res.json(await db.faculty.update({ where: { id: req.params.id }, data: p.data })) });
app.delete('/api/faculties/:id',auth,admin,async(req,res)=>{await db.faculty.delete({where:{id:req.params.id}});res.status(204).end()});
app.post('/api/departments',auth,admin,async(req,res)=>{const p=z.object({name:z.string().min(2),facultyId:z.string(),description:z.string().optional()}).safeParse(req.body);if(!p.success)return res.status(422).json({errors:p.error.flatten()});const slug=p.data.name.toLowerCase().replace(/[^a-z0-9]+/g,'-')+'-'+p.data.facultyId.slice(-5);res.status(201).json(await db.department.create({data:{...p.data,slug}}))});
app.put('/api/departments/:id', auth, admin, async (req, res) => { const p = z.object({ name: z.string().min(2).optional(), facultyId: z.string().optional(), description: z.string().optional() }).safeParse(req.body); if (!p.success) return res.status(422).json({ errors: p.error.flatten() }); res.json(await db.department.update({ where: { id: req.params.id }, data: p.data })) });
app.delete('/api/departments/:id',auth,admin,async(req,res)=>{await db.department.delete({where:{id:req.params.id}});res.status(204).end()});
app.post('/api/courses',auth,admin,async(req,res)=>{const p=z.object({code:z.string(),name:z.string(),departmentId:z.string(),level:z.string(),description:z.string().optional()}).safeParse(req.body);if(!p.success)return res.status(422).json({errors:p.error.flatten()});res.status(201).json(await db.course.create({data:p.data}))});
app.put('/api/courses/:id', auth, admin, async (req, res) => { const p = z.object({ code: z.string().optional(), name: z.string().min(2).optional(), departmentId: z.string().optional(), level: z.string().optional(), description: z.string().optional() }).safeParse(req.body); if (!p.success) return res.status(422).json({ errors: p.error.flatten() }); res.json(await db.course.update({ where: { id: req.params.id }, data: p.data })) });
app.delete('/api/courses/:id',auth,admin,async(req,res)=>{await db.course.delete({where:{id:req.params.id}});res.status(204).end()});
app.get('/api/materials',async(req,res)=>{const q=req.query;const page=Math.max(1,Number(q.page)||1),limit=Math.min(50,Number(q.limit)||12);const where:any={AND:[q.q?{OR:[{title:{contains:String(q.q),mode:'insensitive'}},{description:{contains:String(q.q),mode:'insensitive'}}]}:{},q.faculty?{facultyId:String(q.faculty)}:{},q.department?{departmentId:String(q.department)}:{},q.level?{level:String(q.level)}:{},q.type?{materialType:String(q.type)}:{}]};const [data,total]=await db.$transaction([db.material.findMany({where,skip:(page-1)*limit,take:limit,include:{course:true,faculty:true,department:true}}),db.material.count({where})]);res.json({data,total,page,limit})});
app.get('/api/materials/:id',async(req,res)=>{const m=await db.material.findUnique({where:{id:req.params.id},include:{course:true,faculty:true,department:true,uploadedBy:{select:{fullName:true}}}});if(!m)return res.status(404).json({message:'Material not found'});await db.material.update({where:{id:m.id},data:{views:{increment:1}}});res.json(m)});
app.post('/api/materials',auth,admin,async(req:any,res)=>{const p=z.object({title:z.string().min(3),description:z.string().min(10),fileUrl:z.string().url(),fileName:z.string(),fileSize:z.number().int().positive(),mimeType:z.enum(['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document']),materialType:z.string(),facultyId:z.string(),departmentId:z.string(),level:z.string(),academicSession:z.string(),courseId:z.string().optional()}).safeParse(req.body);if(!p.success)return res.status(422).json({errors:p.error.flatten()});const title=p.data.title;const m=await db.material.create({data:{...p.data,slug:title.toLowerCase().replace(/[^a-z0-9]+/g,'-')+'-'+Date.now(),uploadedById:req.user.sub} as any});res.status(201).json(m)});
app.post('/api/materials/:id/bookmark',auth,async(req:any,res)=>res.json(await db.bookmark.upsert({where:{userId_materialId:{userId:req.user.sub,materialId:req.params.id}},update:{},create:{userId:req.user.sub,materialId:req.params.id}})));
app.put('/api/materials/:id', auth, admin, async (req, res) => { const p = z.object({ title: z.string().min(3).optional(), description: z.string().min(10).optional(), fileUrl: z.string().url().optional(), fileName: z.string().optional(), fileSize: z.number().int().positive().optional(), mimeType: z.enum(['application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document']).optional(), materialType: z.string().optional(), facultyId: z.string().optional(), departmentId: z.string().optional(), level: z.string().optional(), academicSession: z.string().optional(), courseId: z.string().optional() }).safeParse(req.body); if (!p.success) return res.status(422).json({ errors: p.error.flatten() }); res.json(await db.material.update({ where: { id: req.params.id }, data: p.data })) });
app.delete('/api/materials/:id',auth,admin,async(req,res)=>{await db.material.delete({where:{id:req.params.id}});res.status(204).end()});
app.put('/api/users/:id', auth, admin, async (req, res) => { const p = z.object({ displayName: z.string().min(2).optional(), bio: z.string().max(500).optional(), profilePictureUrl: z.string().url().optional(), matricNumber: z.string().min(4).optional() }).safeParse(req.body); if (!p.success) return res.status(422).json({ errors: p.error.flatten() }); res.json(await db.user.update({ where: { id: req.params.id }, data: p.data })) }); app.delete('/api/users/:id',auth,admin,async(req,res)=>{await db.user.delete({where:{id:req.params.id}});res.status(204).end()});
app.listen(Number(process.env.PORT)||4000,()=>console.log('FUW API listening'));
